apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/display-name: Red Hat Advanced Cluster Security Operator
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
  name: rhacs-operator
