apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "10"
  name: redhat-rhpds-gitea
  namespace: gitea-operator
spec:
  sourceType: grpc
  image: quay.io/rhpds/gitea-catalog:latest
  displayName: Red Hat Demo Platform (Gitea)
  publisher: Red Hat Demo Platform