apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-pipelines

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/channel
        value: 'pipelines-1.9'
    target:
      group: operators.coreos.com
      kind: Subscription
      name: openshift-pipelines-operator
      namespace: openshift-operators
      version: v1alpha1
