apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-tools

bases:
# Sonarqube
- sonarqube-admin-secret.yaml
- configure-sonarqube-job.yaml

resources:
  - ../../base
- namespace.yaml

patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: sonarqube:9.9-community
  target:
    kind: Deployment
    name: sonarqube
