apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-vertical-pod-autoscaler

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/channel
        value: 'stable'
    target:
      group: operators.coreos.com
      kind: Subscription
      name: vertical-pod-autoscaler
      namespace: openshift-vertical-pod-autoscaler
      version: v1alpha1
