apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/channel
        value: 'gitops-1.7'
    target:
      group: operators.coreos.com
      kind: Subscription
      name: openshift-gitops-operator
      namespace: openshift-operators
      version: v1alpha1
